-- MySQL Script generated by MySQL Workbench
-- Thu Jul  9 19:12:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema global
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `global` ;

-- -----------------------------------------------------
-- Schema global
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `global` DEFAULT CHARACTER SET utf8 ;
USE `global` ;

-- -----------------------------------------------------
-- Table `global`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `global`.`customer` ;

CREATE TABLE IF NOT EXISTS `global`.`customer` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `nm_name` VARCHAR(45) NOT NULL,
  `nr_cpf_cnpj` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_customer`),
  UNIQUE INDEX `nr_cpf_cnpj_UNIQUE` (`nr_cpf_cnpj` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `global`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `global`.`order` ;

CREATE TABLE IF NOT EXISTS `global`.`order` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `yn_finished` VARCHAR(1) NULL,
  `id_customer` INT NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `fk_order_customer1_idx` (`id_customer` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `global`.`order_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `global`.`order_item` ;

CREATE TABLE IF NOT EXISTS `global`.`order_item` (
  `id_order_item` INT NOT NULL AUTO_INCREMENT,
  `id_order` INT NOT NULL,
  `id_product` INT NOT NULL,
  PRIMARY KEY (`id_order_item`),
  INDEX `fk_order_itens_order1_idx` (`id_order` ASC),
  INDEX `fk_order_itens_product1_idx` (`id_product` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `global`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `global`.`product` ;

CREATE TABLE IF NOT EXISTS `global`.`product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `nm_product` VARCHAR(45) NOT NULL,
  `vl_price` DOUBLE NOT NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
